### ISSUE TITLE
[Maybe a bug] call on onAppear()

### ISSUE THREAD

**Issue by fxsalazar** [NicholasBellucci/StatefulTabView#12]
I'm not sure on which version is a bug (if it even is).
On iOS 13 `onAppear()` gets called only once and never again. But, in iOS 14 it gets called on every show of the Tab.

Tested on my device iOS 14.5 and multiple versions of the simulator: 13.0 - 14.0 - 14.5
The behaviour is consistent on all.

In my case, it helped solve the [TabView issue on iOS 14](https://developer.apple.com/forums/thread/656655). So I use this view only in this version, because I do want the onAppear call. So, thanks?

**Comment by NicholasBellucci** [comment]
Do you have a code sample of where your onAppear and what element it is on?

**Comment by fxsalazar** [comment]
``` swift
import SwiftUI
import StatefulTabView

struct ContentView: View {
    var body: some View {
      StatefulTabView() {
        Tab(title: "1", systemImageName: "map") {
          Text("1")
        }
        Tab(title: "2", systemImageName: "map") {
          Text("2").onAppear{
            debugPrint("called")
          }
        }
        Tab(title: "3", systemImageName: "map") {
          Text("3")
        }
        Tab(title: "4", systemImageName: "map") {
          Text("4")
        }
      }
    }
}
```

**Comment by NicholasBellucci** [comment]
Does moving the on appear to the Tab element and not the Text element fix anything? If not I will try to debug today.

**Comment by fxsalazar** [comment]
I haven't tested it; my use-case is to use it inside the views.

**Comment by NicholasBellucci** [comment]
Seems to me like it might just be a difference in how SwiftUI lays out views on the different versions.
