### ISSUE TITLE
hidesBottomBarWhenPushed

### ISSUE THREAD

**Issue by emelyanovkirill** [NicholasBellucci/StatefulTabView#13]
Is it possible to make an analogue of hidesBottomBarWhenPushed?

**Comment by NicholasBellucci** [comment]
This could be possible. I would need to take a look into it.

**Comment by NicholasBellucci** [comment]
After reviewing this further I do not think this will be possible as that setting needs to occur in a ViewController that is pushed onto the stack and with the way SwiftUI works there isn't a way to properly do this setting. If you have any ideas please let me know but this is what I have gathered so far.

**Comment by MatteCarra** [comment]
I was trying to find possible solutions on how to hide the bottom bar when navigating to a NavigationLink: https://github.com/MatteCarra/StatefulTabView

The current solution I'm testing is to have an Environment object  with an hidden boolean property created by the StatefulTabView: https://github.com/MatteCarra/StatefulTabView/blob/bba8541f7deac1d9adf805b42f5f773a17a0a625/Sources/StatefulTabView/StatefulTabView.swift#L47
NavigationLink destination that want to hide the tab bar will change that environment object onAppear and onDisappear, with a [convenient modifier](https://github.com/MatteCarra/StatefulTabView/blob/master/Sources/StatefulTabView/Modifiers/NavigationLink%2BModifiers.swift): https://github.com/MatteCarra/StatefulTabView/blob/bba8541f7deac1d9adf805b42f5f773a17a0a625/Example/Example/ContentView.swift#L22

I'm very unexperienced with both SwiftUI and particularly with UIKit.
How do I hide the tab bar and make the view fill the entire space.
Currently the tab bar is hidden, but the space is not used and I get an empty area at the bottom: https://github.com/MatteCarra/StatefulTabView/blob/bba8541f7deac1d9adf805b42f5f773a17a0a625/Sources/StatefulTabView/Helpers/TabBarController.swift#L40

Would this solution be good enough for your project?
How do I make SwiftUI tabs use the space left by the hidden tab bar?

Thanks in advance

**Comment by MatteCarra** [comment]
I've noticed you have re-opened the issue.
What are you thinking about that?
Thanks in advance

**Comment by NicholasBellucci** [comment]
I have re-opened to remind myself to look when I have some time. I will say though if there are issues with bottom space being empty and it seems consistent I won't be able to add this solution as I am unsure the fix.
