### ISSUE TITLE
feature-request: unselectedItemTintColor

### ISSUE THREAD

**Issue by moh-abk** [NicholasBellucci/StatefulTabView#7]
Can we get the `UITabBar.appearance().unselectedItemTintColor` modifier? 😻

**Comment by NicholasBellucci** [comment]
I don't see why not! I will look into this today.

**Comment by NicholasBellucci** [comment]
I have made a change on [this](https://github.com/NicholasBellucci/StatefulTabView/tree/feature/unselected-tint-color) branch. Feel free to test this solution. I will merge this into master at some point today.

**Comment by NicholasBellucci** [comment]
Finished as of https://github.com/NicholasBellucci/StatefulTabView/pull/8
