### ISSUE TITLE
bug: opening modals reset tab view to first page

### ISSUE THREAD

**Issue by moh-abk** [NicholasBellucci/StatefulTabView#9]
I just started using the package and noticed that any of my views that is part of the tab view and has a modal when the modal opens it resets the selected index and returns it to zero.

**Comment by NicholasBellucci** [comment]
Are you able to provide a snippet of your code? I can look at it later today and see if its a specific issue with the library.

**Comment by moh-abk** [comment]
I just started building with it so don't have much;

ContentView with 3 tabs (3 views) -- all views have a button that open `sheet`

**Comment by NicholasBellucci** [comment]
This should be resolved in the newest release.

**Comment by moh-abk** [comment]
Awesome - tested.
